services:
  server:
    container_name: server
    build: ./server
    image: krisboorger/moodle-utils:latest
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - CERT=
      - KEY=
      - AUTOSAVE=30s
      - SAVEFILE=/etc/server.json
      - LOGFILE=/log/server.txt
      - CONSOLE_LOGLVL=warn
      - FILE_LOGLVL=info
