services:
  server:
    container_name: moodle-utils-server
    build: ./server
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - AUTOSAVE=30s
      - SAVEFILE=/etc/server.json
      - LOGFILE=/log/server.txt
      - CONSOLE_LOGLVL=warn
      - FILE_LOGLVL=info
